### ISSUE TITLE
Yolo_Nano pretrained model in Google Disk ?

### ISSUE THREAD

**Issue by gillmac13** [lingtengqiu/Yolo_Nano#3]
Hi @lingtengqiu,

Thank you for making available your implementation of Yolo_Nano!
I intend to experiment with it and wonder if you could make your pretrained model available on Google Disk or GoogleDrive as I cannot access the Baidu cloud from outside China.
Thanks in advance :=)

**Comment by lingtengqiu** [comment]
Could you give me your email which can receive files more than 22M?
I just sent your weight but refuse due to a bit bigger.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"安慕希呀安慕希"<1259738366@qq.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 晚上9:26
收件人:&nbsp;"lingtengqiu/Yolo_Nano"<reply@reply.github.com&gt;;

主题:&nbsp;回复：[lingtengqiu/Yolo_Nano] Yolo_Nano pretrained model in Google Disk ? (#3)



That's all,&nbsp; but I think you'd better train your model again. Because this weight got by different process(perhaps in mean and std)
------------------ 原始邮件 ------------------
发件人:&nbsp;"gillmac13"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 晚上9:21
收件人:&nbsp;"lingtengqiu/Yolo_Nano"<Yolo_Nano@noreply.github.com&gt;;
抄送:&nbsp;"安慕希呀安慕希"<1259738366@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;[lingtengqiu/Yolo_Nano] Yolo_Nano pretrained model in Google Disk ? (#3)




Hi @lingtengqiu,
 
Thank you for making available your implementation of Yolo_Nano!
 I intend to experiment with it and wonder if you could make your pretrained model available on Google Disk or GoogleDrive as I cannot access the Baidu cloud from outside China.
 Thanks in advance :=)

**Comment by gillmac13** [comment]
Hi,
It was very nice of you to try. But yes, the file is 22MB but appears as
44MB in gmail due to their coding process, way over their 25MB limit. Same
with all my other e-mail accounts.
So if you don't bother  connecting to https://wetransfer.com and then
clicking the "take me to free" option, you can probably successfully send
the file.

Anyway, thanks again for your efforts,
Gilles

Le jeu. 16 janv. 2020 à 14:32, Lingteng Qiu <notifications@github.com> a
écrit :

**Comment by jgabriellima** [comment]
HI @lingtengqiu and @gillmac13 can you guys share the yolo-nano weight with me please? I would like to execute some testes. thank you!

**Comment by lingtengqiu** [comment]
Now, It's Chinease spring festival, I already gone home, sorry. if you are no hurry,  wait me until 2.4

**Comment by xerus1007** [comment]
Hi @lingtengqiu , can you share the yolo-nano weight on GoogleDrive please? 
I need your weight to execute some tests.

many thanks!

**Comment by nvnnghia** [comment]
I also interest to have the pretrained weights in google drive. Can anyone please upload it and share with us?

**Comment by nvnnghia** [comment]
[updated] I've retrained the model and here is the [checkpoint](https://www.kaggle.com/nvnnghia/yolo-nano). The best mAP is around 0.5 (I kept all default config)
